name: "onnx-model"
platform: "onnxruntime_onnx"
max_batch_size: 8

input [
  {
    name: "X"
    data_type: TYPE_FP32
    dims: [4]
  }
]
output [
  {
    name: "probabilities"
    data_type: TYPE_FP32
    dims: [3]
  }
]

instance_group [
    {
        count: 1
        kind: KIND_CPU
    }
]
