name: "ensemble-onnx"
platform: "ensemble"

input [
    {
        name: "X"
        data_type: TYPE_FP32
        dims: [4] 
    }
]

output [
    {
        name: "labels"
        data_type: TYPE_INT64
        dims: [1]
    }
]

ensemble_scheduling {
    step [
        {
            model_name: "onnx-model"
            model_version: -1
            input_map {
                key: "X"
                value: "X"
            }
            output_map {
                key: "probabilities"
                value: "probabilities"
            }
        },
        {
            model_name: "argmax-model"
            model_version: -1
            input_map {
                key: "probabilities"
                value: "probabilities"
            }
            output_map {
                key: "labels"
                value: "labels"
            }
        }
    ]
}